stages:
  - sync_with_github

sync_with_github:
  stage: sync_with_github
  only:
    - develop
  script:
    - git remote add github https://$GITHUB_TOKEN@github.com/Devluizpozza/estacionAqui.git
    - git push github develop
