stages:
  - deploy

deploy_to_github:
  stage: deploy
  only:
    - develop
  script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$GITHUB_SSH_KEY" | base64 -d | ssh-add -
    - mkdir -p ~/.ssh
    - ssh-keyscan github.com >> ~/.ssh/known_hosts
    - git remote add github git@github.com:Devluizpozza/estacionAqui.git
    - git push github develop:develop