stages:
  - sync_with_github

sync_with_github:
  stage: sync_with_github
  only:
    - develop
  image: alpine:latest
  before_script:
    - apk add --no-cache git
  script:
    # Adiciona o remote do GitHub com token usando 'oauth2' como usuário
    - git remote add github https://oauth2:$GITHUB_TOKEN@github.com/Devluizpozza/estacionAqui.git

    # Cria a branch develop a partir do HEAD atual
    - git checkout -b develop

    # Faz o push da branch develop para o GitHub
    - git push github develop --force
